### ISSUE TITLE
Reminder: if requesting URL from upstream server, make sure Accept-Encoding: header is known

### ISSUE THREAD

**Issue by bmo** [evanmiller/mod_zip#21]
mod_zip doesn't perform well when the upstream server(s) return content that is compressed. 

Here's what you DO NOT WANT to be sending to your upstream: Accept-Encoding: gzip,deflate,sdch

To avoid this, in your upstream subrequest, set the header in a location using:
proxy_set_header Accept-Encoding "";

**Comment by evanmiller** [comment]
Thanks, I've added a note to the README: https://github.com/evanmiller/mod_zip/commit/d63a847e9015bce095b5b1554d5a9f61cbb98060
