### ISSUE TITLE
without upstream, mod_zip does not work

### ISSUE THREAD

**Issue by weizetao** [evanmiller/mod_zip#25]
make response body by ngx_lua ,my code:
ngx.header['X-Archive-Files'] = 'zip'
ngx.say('- 5866317 /disk/20140125/462b4ae8.apk /ac/test.apk')

mod_zip does not work

but use php by fastcgi to make response is ok.

mod_zip only supports upstream to make response body, Friendship is not!

**Comment by anthonyryan1** [comment]
@weizetao Could I ask you to confirm that this proposed change will continue to support your use case? I'd just like to make sure I'm not causing you any regressions with this pending pull request.

https://github.com/anthonyryan1/mod_zip/commit/aab1e2b7ad97f68ad6151c4a9af8d64aba3b790d

**Comment by weizetao** [comment]
@anthonyryan1  To support my use case well, Thanks for your patch.
