### ISSUE TITLE
Compile error on linux with glibc version lower than 2.9

### ISSUE THREAD

**Issue by qiaoba** [evanmiller/mod_zip#33]
Hi, I'm trying to get nginx mod_zip and lua working together. But I was encountered when building nginx with mod_zip module.

My nginx version is nginx-1.2.9, and here is my linux version.
$ cat /proc/version 
Linux version 2.6.32_1-11-0-0  (gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) ) #1 SMP Mon May 20 14:01:01 CST 2013

Here is my building steps:
$ ./configure --prefix=/home/qiaoba/nginx/mynginx --with-debug --with-http_stub_status_module --with-http_realip_module --with-http_image_filter_module --add-module=/home/qiaoba/nginx/mod_zip-master --add-module=/home/soft/output/nginx/src/lua-nginx-module-0.9.7 --add-module=/home/qiaoba/nginx/echo-nginx-module-0.56

$ make

And It occurs after the 'make' command. Part of the errors is pasted here.

make -f objs/Makefile
make[1]: cd “/home/qiaoba/nginx/nginx-1.2.9”
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /home/local/include/luajit-2.0 -I /home/soft/output/nginx/src/lua-nginx-module-0.9.7/src/api -I objs -I src/http -I src/http/modules -I src/mail \
       -o objs/addon/mod_zip-master/ngx_http_zip_file.o \
       /home/qiaoba/nginx/mod_zip-master/ngx_http_zip_file.c
/home/qiaoba/nginx/mod_zip-master/ngx_http_zip_file.c: function ‘ngx_http_zip_file_header_chain_link’中:
/home/qiaoba/nginx/mod_zip-master/ngx_http_zip_file.c:440:5: error：Implicit Declaration ‘htole32’ [-Werror=implicit-function-declaration]
/home/qiaoba/nginx/mod_zip-master/ngx_http_zip_file.c:441:5:  error：Implicit Declaration‘htole16’ [-Werror=implicit-function-declaration]
/home/qiaoba/nginx/mod_zip-master/ngx_http_zip_file.c:455:9:  error：Implicit Declaration‘htole64’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[1]: **\* [objs/addon/mod_zip-master/ngx_http_zip_file.o] error 1
make[1]: get out “/home/qiaoba/nginx/nginx-1.2.9”
make: **\* [build] error 2

**Comment by nelson2005** [comment]
I have the same problem- any chance of a fix being added to the repository?

**Comment by qiaoba** [comment]
@nelson2005 Sure. I'll get into it.

**Comment by nelson2005** [comment]
thanks
