### ISSUE TITLE
Compile Error on Mac OS X 10.9

### ISSUE THREAD

**Issue by wolfman2000** [evanmiller/mod_zip#35]
The following takes place during `make` when I configure nginx with mod_zip:

```
ngx_http_zip_parsers.c:158:18: error: unused variable 'request_error'
      [-Werror,-Wunused-const-variable]
static const int request_error = 0;
                 ^
ngx_http_zip_parsers.c:160:18: error: unused variable 'request_en_main'
      [-Werror,-Wunused-const-variable]
static const int request_en_main = 1;
                 ^
ngx_http_zip_parsers.c:418:18: error: unused variable 'range_error'
      [-Werror,-Wunused-const-variable]
static const int range_error = 0;
                 ^
ngx_http_zip_parsers.c:420:18: error: unused variable 'range_en_main'
      [-Werror,-Wunused-const-variable]
static const int range_en_main = 1;
                 ^
```

The default compiler is clang if it matters.

**Comment by anthonyryan1** [comment]
These are added by the [ragel state machine compiler](http://www.colm.net/open-source/ragel/) when compiling [ngx_http_zip_parsers.rl](https://github.com/evanmiller/mod_zip/blob/master/ngx_http_zip_parsers.rl).

I'll update this issue as I learn more.

**Comment by evanmiller** [comment]
This commit should fix the warnings:

https://github.com/evanmiller/mod_zip/commit/9a261a8a1eda1ab54a62e468e69f6ba85057e5ff

**Comment by anthonyryan1** [comment]
@evanmiller I'm afraid that commit was a bit overzealous.

I believe you want `write data noerror;` rather than `write data noerror nofinal;`.

**Comment by evanmiller** [comment]
Whoops, thanks. Try this:

https://github.com/evanmiller/mod_zip/commit/4db5ed961d747971a6922f0f0d9610b1dfd64698

**Comment by anthonyryan1** [comment]
@wolfman2000 I'm closing this assuming your issue was properly fixed, please re-open this issue if you continue to experience this problem.
