### ISSUE TITLE
Tmp file or actual stream

### ISSUE THREAD

**Issue by btmdave** [evanmiller/mod_zip#36]
My understanding was that this module will stream a zip (while being created) to the browser, however in that case we wouldn't know the content-length.  In practice as we've been using it however, the content-length is available, so does mod_zip create a tmp zip file behind the scenes to get the content-length?

Thank you

**Comment by evanmiller** [comment]
Content-Length is calculated using the file manifest (assuming it contains
the lengths of all the files).

On Tue, Feb 10, 2015 at 6:59 PM, Dave Squires <notifications@github.com>
wrote:

> My understanding was that this module will stream a zip (while being
> created) to the browser, however in that case we wouldn't know the
> content-length. In practice as we've been using it however, the
> content-length is available, so does mod_zip create a tmp zip file behind
> the scenes to get the content-length?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanmiller/mod_zip/issues/36>.
>



-- 
Evan Miller
http://www.evanmiller.org/

**Comment by btmdave** [comment]
Wouldn't that be the wrong total length though? the size of the actual files, not the size of the compressed zip?

**Comment by evanmiller** [comment]
The module does the correct calculation. The constituent files are not compressed so it's not too hard.
