### ISSUE TITLE
implicit declaration of function ‘ngx_http_upstream_header_variable’

### ISSUE THREAD

**Issue by FujiMakoto** [evanmiller/mod_zip#57]
Trying to build Nginx 1.11.10 with mod_zip on Debian Jessie fails with the following error,

```
/usr/local/src/nginx/extensions/mod_zip/ngx_http_zip_file.c: In function ‘ngx_http_zip_generate_pieces’:
/usr/local/src/nginx/extensions/mod_zip/ngx_http_zip_file.c:253:5: error: implicit declaration of function ‘ngx_http_upstream_header_variable’ [-Werror=implicit-function-declaration]
     if(ngx_http_upstream_header_variable(r, vv, (uintptr_t)(&ngx_http_zip_header_name_separator)) == NGX_OK && !vv->not_found) {
     ^
/usr/local/src/nginx/extensions/mod_zip/ngx_http_zip_module.c: In function ‘ngx_http_zip_main_request_header_filter’:
/usr/local/src/nginx/extensions/mod_zip/ngx_http_zip_module.c:197:9: error: implicit declaration of function ‘ngx_http_upstream_header_variable’ [-Werror=implicit-function-declaration]
         variable_header_status = ngx_http_upstream_header_variable(r, vv,
cc1: all warnings being treated as errors
objs/Makefile:1535: recipe for target 'objs/addon/mod_zip/ngx_http_zip_module.o' failed
make[1]: *** [objs/addon/mod_zip/ngx_http_zip_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
objs/Makefile:1549: recipe for target 'objs/addon/mod_zip/ngx_http_zip_file.o' failed
make[1]: *** [objs/addon/mod_zip/ngx_http_zip_file.o] Error 1
make[1]: Leaving directory '/usr/local/src/nginx/source/nginx-1.11.10'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by anthonyryan1** [comment]
This regression was introduced in: http://hg.nginx.org/nginx/rev/d2b2ff157da5

**Comment by Schamschula** [comment]
I'm getting a related error building nginx 1.11.10 under MacPorts:

`	-L/opt/local/lib -L/opt/local/lib -Wl,-headerpad_max_install_names -lexpat -L/opt/local/lib -lluajit-5.1 -lm -ldl -pagezero_size 10000 -image_base 100000000 -lpcre -lssl -lcrypto -lz -lxml2 -lxslt -lexslt
Undefined symbols for architecture x86_64:
  "_ngx_http_upstream_header_variable", referenced from:
      _ngx_http_zip_header_filter in ngx_http_zip_module.o
ld: symbol(s) not found for architecture x86_64
`

**Comment by chrme** [comment]
@FujiMakoto _a quickfix_: just move defn **ngx_http_upstream_header_variable** from the beginning of _ngx_http_upstream.c_ to the _ngx_http_upstream.h_, change it to non-static and change func **ngx_http_upstream_header_variable** in the _ngx_http_upstream.c_ to non-static

**Comment by evanmiller** [comment]
Fixed in  https://github.com/evanmiller/mod_zip/commit/a7f9f8bed53a9599931caf505a655f8dc4c640a6
