### ISSUE TITLE
Downloading stops after severalk kb's on CentOS version 6 nginx 1.10.2 

### ISSUE THREAD

**Issue by Pelmen2la** [evanmiller/mod_zip#59]
I am using mod_zip for mp3 files.
On one server CentOS version 7 nginx 1.10.2 and plugin works clean.
On another with CentOS version 6 nginx 1.10.2 sometimes resposne stops after downloading several kb's. It depends on files count.

Does anybody know why this error occurs?

**Comment by dup2** [comment]
Might be an issue with the open files limit? Each file included in the zip triggers AFAIK a sub request which in turn uses a file handle kept open while building the zip. You might want to see https://www.masv.io/boost-nginx-connection-limits/ for changing this.

**Comment by Pelmen2la** [comment]
The files are same on each server. Count and content are identical.

**Comment by evanmiller** [comment]
Hi, if you can turn on debugging (`error_log /path/to/log debug;`) and share the log output I will try to figure out what's going on.

**Comment by evanmiller** [comment]
Also, does your issue look like #55?
