### ISSUE TITLE
zip files created cannot be unzipped on Mac OS X (10.6) with default unarchiver (Error- 1 Operation not permitted)

### ISSUE THREAD

**Issue by khelben** [evanmiller/mod_zip#6]
I have a web app where I use nginx + mod_zip (HEAD version of repo).

Every zip created with mod_zip give me an 'Error- 1 Operation not permitted' error when I use the default unarchiver from Mac OS, using StuffIt expander solves this issue.

Any reason why these zips cannot be unarchived using the default tool?

TIA

Christiaan

**Comment by anthonyryan1** [comment]
Closing the issue because Apple resolved this problem on their end in OS X 10.8.

Anyone affected on a newer version of OS X is welcome to open a new issue.
