### ISSUE TITLE
Dynamically generating file list

### ISSUE THREAD

**Issue by jkburges** [evanmiller/mod_zip#65]
From the README:

> It then scans the response body for a list of files. The syntax is a space-separated list of the file checksum (CRC-32), size (in bytes), location (properly URL-encoded), and file name. One file per line.

Regarding the list of files, is there a module that you know of, or some other easy way, to generate the list in the correct format, given some path? e.g. given path `/some/dir`, generate a list of all files under that path (recursively)?

**Comment by jkburges** [comment]
I've got a bash script which I *think* generates a manifest:

```
#!/bin/bash
DIR=$1

for FILE in `find $DIR -type f`; do
    echo -n '- ';
    stat --printf="%s " ${FILE}
    echo -n "${FILE} "
    echo "${FILE}"
done
```

**Comment by dup2** [comment]
We provide a ruby gem for this at https://github.com/cargoserver/ngzip - if you use ruby, this might help.

**Comment by jkburges** [comment]
Thanks @dup2 - we do actually use ruby for some things (and the gem looks good). I do think it'd be a shame to have to introduce a dependency on ruby though for something (relatively) simple - seems as though the build in auto indexing *almost* gets the job done.

I'll keep looking for a bit!

**Comment by dcsobral** [comment]
Here's a bash script that works (requires packages `fcgiwrap` and `libarchive-zip-perl`). It copies files into a "download" subdirectory to avoid errors resulting from files being modified (if the size changes, `mod_zip` will produce corrupted zip files). The prefix for the download path should be passed as `FILES_PREFIX`, or it defaults to `/files`. The folder to download should be passed as a query string. Finally, it takes a `MASK` parameter which is used to select which files to download.

To be honest, this is a way more complicated version of the script I had originally, just to make it flexible enough to be easily used without changes for various purposes.

```bash
#!/bin/bash
set -euo pipefail  # unofficial bash lint mode

FILES_PREFIX=${FILES_PREFIX-/files}
DIR="${QUERY_STRING%/}"
DOWNLOAD="${DIR}/download"

sanitize() {
  echo "$1" | sed 's/\\/\\\\/g;s/"/\\"/g'
}

listenv() {
  while IFS= read -r name; do
    cat <<-EOF
			"$name": "$(sanitize "${!name}")",
		EOF
  done < <(printenv | sed 's;=.*;;' | sort)
}

errmsg() {
  cat <<-EOF
		{
		  $(listenv)
		  "message": "$(sanitize "$1")"
		}
	EOF
}

mkdir -p "${DOWNLOAD}" 2> /dev/null || :

if [[ ! -w "${DOWNLOAD}" || ! -d "${DOWNLOAD}" ]]; then
  echo "Status: 500 Download folder misconfiguration"
  echo
  errmsg "${DOWNLOAD}: $(ls -ld "${DOWNLOAD}" || echo "not found")"
  exit 1
fi

abort_copy() {
  echo "Status: 500 Download file copy error"
  echo
  errmsg "$MSG"
  exit 1
}

trap abort_copy EXIT

while IFS= read -r -d '' FILE; do
  SUBDIR=$( dirname "${FILE#${DIR}/}" )
  MSG=$( [[ -n $SUBDIR ]] && mkdir -p "${DOWNLOAD}/${SUBDIR}" 2>&1 )
  MSG=$( cp -f "${FILE}" "${DOWNLOAD}/${SUBDIR}/$(basename "${FILE}")" 2>&1 )
done < <(find "${DIR}" -path "${DOWNLOAD}" -prune -or -name "$MASK" -type f -print0)

trap - EXIT

echo "Status: 200 OK"
echo

while IFS= read -r -d '' FILE; do
  NAME="${FILE#${DOWNLOAD}/}"
  CRC="$( crc32 "${FILE}" )"
  SIZE="$( stat --printf="%s" "${FILE}" )"
  printf "%s %s ${FILES_PREFIX}/%s %s\n" "${CRC}" "${SIZE}" "${NAME}" "${NAME}"
done < <(find "${DOWNLOAD}" -type f -print0)
```

Nginx `default` configuration would be something like below. In this example the path `/images/folder/` will download all `png` files under `/usr/share/nginx/http/files/folder/`.

```
upstream folderlist {
  server localhost:8081;
}

server {
  listen 8081;
  server_name localhost;

  location ~ ^/([^/]*)$ {
    root /usr/share/nginx/http/files;
    add_header X-Archive-Files 'zip';
    add_header Content-Disposition "attachment; filename=$1.zip";
    fastcgi_pass unix:/var/run/fcgiwrap.socket;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /usr/share/nginx/http/cgi-bin/listfiles.sh;
    fastcgi_param QUERY_STRING $request_filename;
    fastcgi_param FILES_PREFIX $arg_prefix;
    fastcgi_param MASK $arg_mask;
  }
}

server {
  listen 80;
  server_name localhost;

  location /files/ {
    root /usr/share/nginx/http/files/download;
    rewrite ^/files/(.*)$ /$1 break;
  }

  location ~ ^/images(/(.*/|)$ {
    default_type application/octet-stream;
    gzip on;
    gzip_vary on;
    gzip_http_version 1.1;
    gzip_types application/octet-stream application/zip;
    proxy_pass http://folderlist/$1?prefix=/files&mask=*.png;
    proxy_pass_request_headers off;
  }
}
```

**Comment by arnaud** [comment]
A bit late in the file list generation game, but here's our take on this task:

https://github.com/BouyguesTelecom/a7/blob/main/scripts/generate-directories-metadata.sh#L29-L47
