### ISSUE TITLE
the mod_zip can't support compressed files download

### ISSUE THREAD

**Issue by justquanyin** [evanmiller/mod_zip#66]
Example:
 the output : 
  ```
   - 243410 /1.jpg 1.jpg 
   - 13524697 /2.zip 2.zip
```
the response header:
```
X-Archive-Files:zip;
Content-Disposition:attachment; filename=all.zip;
Content-Type:application/octet-stream
```

When  the `all.zip` file  has been downloaded , unzip the `all.zip` , got the `2.zip` . But I can't unzip the 2.zip . The System Error  is `The document “2.zip ” could not be opened. The file isn’t in the correct format.`

Please help me , thanks .

**Comment by evanmiller** [comment]
Hi, you will need to provide example files that demonstrate the problem.
