### ISSUE TITLE
No check for r->upstream validity in ngx_http_zip_generate_pieces

### ISSUE THREAD

**Issue by mikhail-nikitin** [evanmiller/mod_zip#68]
Hello,

When there is no upstream and content is generated with openresty's content_by_lua or the likes, the
value of r->upstream is NULL, so ngx_http_variable_unknown_header causes nginx to crash (ngx_http_zip_file.c:253). 

The old ngx_http_upstream_header_variable has a check for upstream null value before calling ngx_http_variable_unknown_header. 

Pull request - #69

**Comment by legalimpurity** [comment]
This just made my day. Thanks mikhail. Would like to see this merged.

**Comment by evanmiller** [comment]
Merged, thanks for testing!
