### ISSUE TITLE
File modification dates

### ISSUE THREAD

**Issue by iceman** [evanmiller/mod_zip#7]
Nginx is logging in my server's local timezone.  But the files within the zip are the download time in GMT after extracting.  Is there any way to set this so that the dates aren't (for me) five hours in the future.

**Comment by evanmiller** [comment]
mod_zip stores the UTC date in the "extended timestamp" field, so modern ZIP unarchivers should set the timestamp correctly. (The old DOS timestamp field is unaware of time zones, so older ZIP unarchivers will treat the UTC date as the local date.)

**Comment by bennnjamin** [comment]
@evanmiller My timestamp is not set correctly on downloads coming from S3. The peculiar thing is the folders are created correctly in local time but the files themselves are showing date modified in UTC/GMT (in the future for me)

Mac OS X, Archiver Utility
