### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by martin-sucha** [evanmiller/mod_zip#71]
I could not find any license file in this git repository nor any mention in the readme. Which license does the project use? Could you [add the LICENSE file](
https://help.github.com/articles/adding-a-license-to-a-repository/)?

**Comment by tomicooler** [comment]
Hi!

On the old code.google page I saw that it is licensed under New BSD License. Could you upload the license for this github repository as well?

Also maybe make a tag/release with the latest stable version?

That would be really great, thank you!

**Comment by evanmiller** [comment]
Done
