### ISSUE TITLE
Need a release

### ISSUE THREAD

**Issue by dvershinin** [evanmiller/mod_zip#72]
There seems to be a lot of changes since the last release. Is it possible to tag one [here](
https://github.com/evanmiller/mod_zip/releases)?

This would help with packaging the module as RPM into [nginx extras](https://extras.getpagespeed.com/redhat/7/x86_64/repoview/letter_n.group.html) RPM repository.

**Comment by evanmiller** [comment]
Ask and ye shall receive! (After 2 years)

https://github.com/evanmiller/mod_zip/releases
