### ISSUE TITLE
Manipulate directory paths in zipfile output

### ISSUE THREAD

**Issue by mecampbellsoup** [evanmiller/mod_zip#76]
Hi guys,

Just began using `mod_zip` recently - I have a setup working ATM whereby NGINX is serving zipfile requests; however, I want to know if it is possible to modify the directory paths in the unzipped contents.

The following screenshot should explain my question...

![image](https://user-images.githubusercontent.com/2043821/97084243-bf873200-15e3-11eb-9718-345eed570796.png)

Instead of all the leading directory paths, I would prefer the output contents to omit those leading paths and simply unzip to the `*.tif` files contained at `/mnt/data/userdata/{userhash}/outputs/cinema4d/23.008/{project-name}/{file-name}`.

I imagine this _should_ be possible using some NGINX rewrite or some other modification to my location, which looks like:

```nginx
        # mod_zip location helper
        # Note: The leading ^~ is essential here, no more checks should be done after this match
        location ^~ /mnt/data/userdata/ {
            internal;
        	root /;
        }
```

Thanks for your thoughts/help.

**Comment by evanmiller** [comment]
Hi, you can specify the output path in the manifest file.

**Comment by mecampbellsoup** [comment]
Ah, yea, thanks @evanmiller - the library I was using to generate the manifest for NGINX was doing something unexpected. All resolved, cheers.
