### ISSUE TITLE
Range in subrequests 

### ISSUE THREAD

**Issue by furk** [evanmiller/mod_zip#8]
If the original request is a Range request then subrequest doesn't use Range header. 
So if a zip contains for example 2x 10G files and Range request was made for the last 1G of the second file  then mod will subrequest the whole file and just skip the first 9G of the file.

For a client it looks like a download is not started for 2-3 mins. And since most downloadmanagers have just 60 secs timeout it will fail on such files.

**Comment by evanmiller** [comment]
Hi, this is implemented here: https://github.com/evanmiller/mod_zip/commit/eb3f28ce7d566dbec1095de44f5b821a387e295e

If you have any problems with this feature, please open a new issue.
